name: cloud-infra-manager
description: Cloud Infrastructure Management using Pulumi and GCP
runtime:
  name: python
  options:
    toolchain: pip
config:
  pulumi:tags:
    value:
      pulumi:template: gcp-python
